databases:
  - name: budget_buddy
    databaseName: budget_buddy_ap30
    user: budget_buddy_ap30_user
services:
  - type: web
    name: budget_buddy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_buddy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false