default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_buddy_development
  username: postgres
  password: 12345

test:
  <<: *default
  database: budget_buddy_test
  username: postgres
  password: 12345

production:
  <<: *default
  database: budget_buddy_production
  username: budget_buddy
  password: <%= ENV["BUDGET_BUDDY_DATABASE_PASSWORD"] %>
